// ============================================================
// NOTIFICATION TYPES - Master Constants
// ============================================================

export const NOTIFICATION_TYPES = {
  // ============ PAYMENT & BILLING ============
  PAYMENT_RECEIVED: "payment.received",
  PARTIAL_PAYMENT_RECEIVED: "payment.partial",
  BALANCE_PENDING: "payment.balance_pending",
  PAYMENT_DUE: "payment.due",
  PAYMENT_OVERDUE: "payment.overdue",
  PAYMENT_FAILED: "payment.failed",
  REFUND_INITIATED: "payment.refund_initiated",
  REFUND_COMPLETED: "payment.refund_completed",
  INVOICE_GENERATED: "payment.invoice_generated",
  RECEIPT_GENERATED: "payment.receipt_generated",

  // ============ APPOINTMENTS ============
  APPOINTMENT_BOOKED: "appointment.booked",
  APPOINTMENT_CONFIRMED: "appointment.confirmed",
  APPOINTMENT_REMINDER: "appointment.reminder",
  APPOINTMENT_RESCHEDULED: "appointment.rescheduled",
  APPOINTMENT_CANCELLED: "appointment.cancelled",
  APPOINTMENT_COMPLETED: "appointment.completed",
  PATIENT_CHECKED_IN: "appointment.checked_in",
  NO_SHOW: "appointment.no_show",
  WAITLIST_AVAILABLE: "appointment.waitlist_available",

  // ============ PACKAGES & MEMBERSHIPS ============
  PACKAGE_PURCHASED: "package.purchased",
  PACKAGE_ACTIVATED: "package.activated",
  SESSION_USED: "package.session_used",
  SESSIONS_REMAINING: "package.sessions_remaining",
  LAST_SESSION_REMAINING: "package.last_session",
  PACKAGE_EXPIRING_30_DAYS: "package.expiring_30days",
  PACKAGE_EXPIRING_7_DAYS: "package.expiring_7days",
  PACKAGE_EXPIRING_1_DAY: "package.expiring_1day",
  PACKAGE_EXPIRED: "package.expired",
  PACKAGE_RENEWED: "package.renewed",
  PACKAGE_TRANSFERRED: "package.transferred",
  SESSION_RECEIVED: "package.session_received",
  MEMBERSHIP_RENEWAL: "membership.renewal",
  MEMBERSHIP_EXPIRY: "membership.expiry",

  // ============ FOLLOW-UP & TREATMENT ============
  TREATMENT_COMPLETED: "treatment.completed",
  FOLLOWUP_DUE: "followup.due",
  FOLLOWUP_OVERDUE: "followup.overdue",
  POST_TREATMENT_MESSAGE: "followup.post_treatment",
  PREPARATION_REMINDER: "followup.preparation_reminder",
  REPORT_AVAILABLE: "treatment.report_available",
  DOCUMENT_AVAILABLE: "treatment.document_available",
  PRESCRIPTION_AVAILABLE: "treatment.prescription_available",

  // ============ PATIENT ENGAGEMENT ============
  BIRTHDAY_GREETING: "engagement.birthday",
  BIRTHDAY_OFFER: "engagement.birthday_offer",
  PATIENT_INACTIVE: "engagement.inactive",
  PATIENT_REACTIVATION: "engagement.reactivation",
  ANNIVERSARY: "engagement.anniversary",
  LOYALTY_REWARD: "engagement.loyalty_reward",

  // ============ OFFERS & REFERRALS ============
  NEW_OFFER: "offer.new",
  OFFER_EXPIRING: "offer.expiring",
  OFFER_REDEEMED: "offer.redeemed",
  REFERRAL_CREATED: "referral.created",
  REFERRAL_COMPLETED: "referral.completed",
  REFERRAL_REWARD_EARNED: "referral.reward_earned",
  REFERRAL_REWARD_USED: "referral.reward_used",

  // ============ FEEDBACK ============
  FEEDBACK_REQUEST: "feedback.request",
  REVIEW_REQUEST: "feedback.review_request",
  NEGATIVE_FEEDBACK_ALERT: "feedback.negative_alert",

  // ============ SECURITY ============
  NEW_LOGIN: "security.new_login",
  ACCOUNT_CHANGED: "security.account_changed",
  CONSENT_CHANGED: "security.consent_changed",
  IMPORTANT_SECURITY_EVENT: "security.important_event",
};

// ============================================================
// NOTIFICATION CATEGORIES
// ============================================================

export const NOTIFICATION_CATEGORIES = {
  PAYMENT: "payment",
  APPOINTMENT: "appointment",
  PACKAGE: "package",
  FOLLOWUP: "followup",
  ENGAGEMENT: "engagement",
  OFFER: "offer",
  FEEDBACK: "feedback",
  SECURITY: "security",
};

// ============================================================
// PROTECTED NOTIFICATION TYPES (Need confirmation before disable)
// ============================================================

export const PROTECTED_NOTIFICATION_TYPES = [
  NOTIFICATION_TYPES.PAYMENT_RECEIVED,
  NOTIFICATION_TYPES.PARTIAL_PAYMENT_RECEIVED,
  NOTIFICATION_TYPES.PAYMENT_FAILED,
  NOTIFICATION_TYPES.REFUND_INITIATED,
  NOTIFICATION_TYPES.REFUND_COMPLETED,
  NOTIFICATION_TYPES.APPOINTMENT_CANCELLED,
  NOTIFICATION_TYPES.PACKAGE_TRANSFERRED,
  NOTIFICATION_TYPES.SESSION_RECEIVED,
  NOTIFICATION_TYPES.NEW_LOGIN,
  NOTIFICATION_TYPES.ACCOUNT_CHANGED,
  NOTIFICATION_TYPES.CONSENT_CHANGED,
  NOTIFICATION_TYPES.IMPORTANT_SECURITY_EVENT,
];

// ============================================================
// MARKETING NOTIFICATION TYPES (Requires patient consent)
// ============================================================

export const MARKETING_NOTIFICATION_TYPES = [
  NOTIFICATION_TYPES.BIRTHDAY_OFFER,
  NOTIFICATION_TYPES.PATIENT_REACTIVATION,
  NOTIFICATION_TYPES.LOYALTY_REWARD,
  NOTIFICATION_TYPES.NEW_OFFER,
  NOTIFICATION_TYPES.OFFER_EXPIRING,
  NOTIFICATION_TYPES.OFFER_REDEEMED,
  NOTIFICATION_TYPES.REFERRAL_CREATED,
  NOTIFICATION_TYPES.REFERRAL_COMPLETED,
  NOTIFICATION_TYPES.REFERRAL_REWARD_EARNED,
  NOTIFICATION_TYPES.REFERRAL_REWARD_USED,
];

// ============================================================
// STAFF ALERT NOTIFICATION TYPES
// ============================================================

export const STAFF_ALERT_NOTIFICATION_TYPES = [
  NOTIFICATION_TYPES.PAYMENT_FAILED,
  NOTIFICATION_TYPES.PACKAGE_EXPIRING_7_DAYS,
  NOTIFICATION_TYPES.PACKAGE_EXPIRING_1_DAY,
  NOTIFICATION_TYPES.FOLLOWUP_OVERDUE,
  NOTIFICATION_TYPES.NEGATIVE_FEEDBACK_ALERT,
  NOTIFICATION_TYPES.NO_SHOW,
  NOTIFICATION_TYPES.IMPORTANT_SECURITY_EVENT,
];

// ============================================================
// MASTER SEED NOTIFICATION DATA
// Matches Setting.js -> notificationSetting schema sequence
// ============================================================

export const notificationData = [
  // ============================================================
  // 1. PAYMENT & BILLING
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.PAYMENT_RECEIVED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Payment Received",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Payment successfully received.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, we have received your payment of AED {{amount}}.\nReceipt No: {{receipt_number}}\nDate: {{date}}\nThank you for choosing {{clinic_name}}.",
    sample: { patient_name: "Rahul", amount: "500", receipt_number: "RC-10482", date: "12 Aug 2026", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PARTIAL_PAYMENT_RECEIVED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Partial Payment Received",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Partial payment received with balance pending.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, we have received your partial payment of AED {{amount_received}}.\nTotal Amount: AED {{total_amount}}\nBalance Pending: AED {{balance}}\nDate: {{date}}\nThank you for choosing {{clinic_name}}.",
    sample: { patient_name: "Rahul", amount_received: "500", total_amount: "1,000", balance: "500", date: "12 Aug 2026", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.BALANCE_PENDING,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Balance Pending",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Invoice has an unpaid balance.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, you have a pending balance of AED {{balance_amount}} with {{clinic_name}}. Please settle your payment by {{due_date}}.",
    sample: { patient_name: "Rahul", balance_amount: "500", due_date: "20 Aug 2026", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PAYMENT_DUE,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Payment Due",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Payment due date is approaching.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "before_event", offsetMinutes: -1440 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, a payment of AED {{amount}} is due on {{due_date}} for {{clinic_name}}. You can pay using this link: {{payment_link}}",
    sample: { patient_name: "Rahul", amount: "500", due_date: "15 Aug 2026", payment_link: "https://zeva.care/pay/10482", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PAYMENT_OVERDUE,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Payment Overdue",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Payment due date has passed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 2880 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your payment of AED {{amount}} to {{clinic_name}} is overdue by {{overdue_days}} days. Please settle your account using this link: {{payment_link}}",
    sample: { patient_name: "Rahul", amount: "500", overdue_days: "3", payment_link: "https://zeva.care/pay/10482", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PAYMENT_FAILED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Payment Failed",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Payment transaction failed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
      { channel: "email", recipient: "staff", isEnabled: true, priority: 4 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your payment attempt of AED {{amount}} to {{clinic_name}} failed. Reason: {{failure_reason}}. You can retry here: {{retry_link}}",
    sample: { patient_name: "Rahul", amount: "500", failure_reason: "Insufficient funds", retry_link: "https://zeva.care/pay/retry/10482", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REFUND_INITIATED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Refund Initiated",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Refund process initiated.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, a refund of AED {{amount}} has been initiated for Refund ID {{refund_id}} by {{clinic_name}}. It will reflect in your account within 3-5 business days.",
    sample: { patient_name: "Rahul", amount: "300", refund_id: "RF-8821", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REFUND_COMPLETED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Refund Completed",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Refund successfully processed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your refund of AED {{amount}} (Refund ID: {{refund_id}}) from {{clinic_name}} has been completed.",
    sample: { patient_name: "Rahul", amount: "300", refund_id: "RF-8821", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.INVOICE_GENERATED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Invoice Generated",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "New invoice generated.", conditions: {} },
    channels: [
      { channel: "email", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your invoice #{{invoice_number}} for AED {{amount}} from {{clinic_name}} is ready. View invoice: {{invoice_link}}",
    sample: { patient_name: "Rahul", invoice_number: "INV-9901", amount: "750", invoice_link: "https://zeva.care/inv/9901", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.RECEIPT_GENERATED,
    category: NOTIFICATION_CATEGORIES.PAYMENT,
    label: "Receipt Generated",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Payment receipt generated.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your payment receipt #{{receipt_number}} for AED {{amount}} from {{clinic_name}} is available. Download receipt: {{receipt_link}}",
    sample: { patient_name: "Rahul", receipt_number: "RC-10482", amount: "500", receipt_link: "https://zeva.care/receipt/10482", clinic_name: "Vedara Care" },
  },

  // ============================================================
  // 2. APPOINTMENTS
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.APPOINTMENT_BOOKED,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Appointment Booked",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "New appointment scheduled.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your appointment at {{clinic_name}} has been booked for {{appointment_date}} at {{appointment_time}} with {{provider}}.\nManage booking: {{booking_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", appointment_date: "15 Aug 2026", appointment_time: "5:00 PM", provider: "Dr. Sarah", booking_link: "https://zeva.care/apt/b821" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.APPOINTMENT_CONFIRMED,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Appointment Confirmed",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Appointment status changed to confirmed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your appointment at {{clinic_name}} on {{appointment_date}} at {{appointment_time}} with {{provider}} is confirmed.",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", appointment_date: "15 Aug 2026", appointment_time: "5:00 PM", provider: "Dr. Sarah" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.APPOINTMENT_REMINDER,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Appointment Reminder",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Appointment is approaching.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "before_event", offsetMinutes: -1440 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your appointment is tomorrow.\nDate: {{appointment_date}}\nTime: {{appointment_time}}\nProvider: {{provider}}\nLocation: {{location}}\nManage appointment: {{booking_link}}",
    sample: { patient_name: "Rahul", appointment_date: "15 Aug 2026", appointment_time: "5:00 PM", provider: "Dr. Sarah", location: "Vedara Care, Suite 402", booking_link: "https://zeva.care/apt/b821" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.APPOINTMENT_RESCHEDULED,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Appointment Rescheduled",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Appointment date/time updated.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your appointment at {{clinic_name}} has been rescheduled from {{old_date}} {{old_time}} to {{new_date}} at {{new_time}} with {{provider}}.",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", old_date: "14 Aug", old_time: "3:00 PM", new_date: "15 Aug 2026", new_time: "5:00 PM", provider: "Dr. Sarah" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.APPOINTMENT_CANCELLED,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Appointment Cancelled",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Appointment cancelled by patient or clinic.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your appointment on {{appointment_date}} at {{appointment_time}} at {{clinic_name}} has been cancelled. Reason: {{cancellation_reason}}.",
    sample: { patient_name: "Rahul", appointment_date: "15 Aug 2026", appointment_time: "5:00 PM", clinic_name: "Vedara Care", cancellation_reason: "Schedule conflict" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.APPOINTMENT_COMPLETED,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Appointment Completed",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Appointment marked as completed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "after_event", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, thank you for visiting {{clinic_name}} today for your session with {{provider}}. Book your next visit: {{next_appointment_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", provider: "Dr. Sarah", next_appointment_link: "https://zeva.care/book" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PATIENT_CHECKED_IN,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Patient Checked In",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient arrives and checks in at reception.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, welcome to {{clinic_name}}! You are checked in. {{provider}} will see you shortly.",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", provider: "Dr. Sarah" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.NO_SHOW,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "No Show",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient missed appointment without cancelling.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 60 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, we missed you today at {{clinic_name}} for your appointment on {{appointment_date}} at {{appointment_time}}. Please reschedule here: {{reschedule_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", appointment_date: "15 Aug 2026", appointment_time: "5:00 PM", reschedule_link: "https://zeva.care/reschedule/b821" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.WAITLIST_AVAILABLE,
    category: NOTIFICATION_CATEGORIES.APPOINTMENT,
    label: "Waitlist Slot Available",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "A cancelled slot opens up for a waitlisted patient.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, a slot just opened up at {{clinic_name}} for {{appointment_date}} at {{appointment_time}}! Claim it now: {{booking_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", appointment_date: "16 Aug 2026", appointment_time: "10:00 AM", booking_link: "https://zeva.care/claim/w902" },
  },

  // ============================================================
  // 3. PACKAGES & MEMBERSHIPS
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_PURCHASED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Purchased",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient purchases a treatment package.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, thank you for purchasing {{package_name}} (Total sessions: {{total_sessions}}). Package expiry: {{expiry_date}}. View package: {{package_link}}",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal (6 Sessions)", total_sessions: "6", expiry_date: "12 Nov 2026", package_link: "https://zeva.care/pkg/772" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_ACTIVATED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Activated",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package status changes to active.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your package {{package_name}} is now active with {{total_sessions}} total sessions at {{clinic_name}}.",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", total_sessions: "6", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.SESSION_USED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Session Used",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package session is recorded as used.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{package_name}} session has been recorded.\nSession used: {{sessions_used}}\nDate: {{date}}\nSessions remaining: {{sessions_remaining}}\nPackage expiry: {{expiry_date}}",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", sessions_used: "1", date: "12 Aug 2026", sessions_remaining: "5", expiry_date: "12 Nov 2026" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.SESSIONS_REMAINING,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Sessions Remaining",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Periodic session balance update.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, you have {{sessions_remaining}} sessions remaining in your {{package_name}} at {{clinic_name}}. Expiry: {{expiry_date}}.",
    sample: { patient_name: "Rahul", sessions_remaining: "3", package_name: "Laser Hair Removal", clinic_name: "Vedara Care", expiry_date: "12 Nov 2026" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.LAST_SESSION_REMAINING,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Last Session Remaining",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package reaches exactly 1 session remaining.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, you have 1 session remaining in your {{package_name}}.\nPackage expiry: {{expiry_date}}.\nContact {{clinic_name}} or book now: {{booking_link}}",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", expiry_date: "12 Nov 2026", clinic_name: "Vedara Care", booking_link: "https://zeva.care/book" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_EXPIRING_30_DAYS,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Expiring (30 Days)",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package expiration is 30 days away.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "before_event", offsetMinutes: -43200 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{package_name}} expires in 30 days on {{expiry_date}}. You have {{sessions_remaining}} sessions remaining. Book now: {{renewal_link}}",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", expiry_date: "12 Nov 2026", sessions_remaining: "4", renewal_link: "https://zeva.care/renew/772" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_EXPIRING_7_DAYS,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Expiring (7 Days)",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package expiration is 7 days away.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "before_event", offsetMinutes: -10080 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{package_name}} expires in 7 days on {{expiry_date}}. You have {{sessions_remaining}} sessions remaining. Don't lose your sessions: {{renewal_link}}",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", expiry_date: "12 Nov 2026", sessions_remaining: "2", renewal_link: "https://zeva.care/renew/772" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_EXPIRING_1_DAY,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Expiring (1 Day)",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package expiration is 1 day away.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "before_event", offsetMinutes: -1440 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{package_name}} expires tomorrow ({{expiry_date}})! You have {{sessions_remaining}} sessions remaining.",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", expiry_date: "12 Nov 2026", sessions_remaining: "1" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_EXPIRED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Expired",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package expiration date has passed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{package_name}} at {{clinic_name}} has expired on {{expiry_date}}. Contact us to renew: {{renewal_link}}",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", clinic_name: "Vedara Care", expiry_date: "12 Nov 2026", renewal_link: "https://zeva.care/renew/772" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_RENEWED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Renewed",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Package renewed by patient.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your package {{package_name}} has been successfully renewed with {{total_sessions}} sessions. New expiry: {{new_expiry_date}}.",
    sample: { patient_name: "Rahul", package_name: "Laser Hair Removal", total_sessions: "6", new_expiry_date: "12 Nov 2027" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PACKAGE_TRANSFERRED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Package Transferred",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Sessions transferred out to another patient.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, {{sessions_transferred}} session from your {{package_name}} has been transferred to {{recipient_name}} on {{transfer_date}}.\nSessions remaining: {{sessions_remaining}}.\nIf you did not authorize this, please contact {{clinic_name}}.",
    sample: { patient_name: "Rahul", sessions_transferred: "1", package_name: "Laser Hair Removal", recipient_name: "Priya", transfer_date: "12 Aug 2026", sessions_remaining: "4", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.SESSION_RECEIVED,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Session Received",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Sessions received via transfer from another patient.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, {{sessions_received}} session of {{package_name}} has been added to your account through a transfer from {{sender_name}} on {{transfer_date}}.",
    sample: { patient_name: "Priya", sessions_received: "1", package_name: "Laser Hair Removal", sender_name: "Rahul", transfer_date: "12 Aug 2026" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.MEMBERSHIP_RENEWAL,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Membership Renewal",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Membership renewal reminder.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "before_event", offsetMinutes: -10080 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{membership_name}} membership at {{clinic_name}} is due for renewal on {{expiry_date}}. Renew now: {{renewal_link}}",
    sample: { patient_name: "Rahul", membership_name: "VIP Care Membership", clinic_name: "Vedara Care", expiry_date: "01 Sep 2026", renewal_link: "https://zeva.care/membership/renew" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.MEMBERSHIP_EXPIRY,
    category: NOTIFICATION_CATEGORIES.PACKAGE,
    label: "Membership Expiry",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Membership expires.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{membership_name}} membership at {{clinic_name}} has expired on {{expiry_date}}. Renew your membership: {{renewal_link}}",
    sample: { patient_name: "Rahul", membership_name: "VIP Care Membership", clinic_name: "Vedara Care", expiry_date: "01 Sep 2026", renewal_link: "https://zeva.care/membership/renew" },
  },

  // ============================================================
  // 4. FOLLOW-UP & TREATMENT
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.TREATMENT_COMPLETED,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Treatment Completed",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Treatment session completed.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "after_event", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{treatment_name}} session at {{clinic_name}} on {{date}} is complete.",
    sample: { patient_name: "Rahul", treatment_name: "Laser Hair Removal", clinic_name: "Vedara Care", date: "12 Aug 2026" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.FOLLOWUP_DUE,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Follow-up Due",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Post-treatment follow-up date reached.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "after_event", offsetMinutes: 2880 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your recommended follow-up for {{treatment_name}} at {{clinic_name}} is now due. Book your appointment: {{booking_link}}",
    sample: { patient_name: "Rahul", treatment_name: "Laser Hair Removal", clinic_name: "Vedara Care", booking_link: "https://zeva.care/book" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.FOLLOWUP_OVERDUE,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Follow-up Overdue",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Follow-up overdue by clinic threshold.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 10080 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your follow-up for {{treatment_name}} at {{clinic_name}} is overdue by {{overdue_days}} days. Book now: {{booking_link}}",
    sample: { patient_name: "Rahul", treatment_name: "Laser Hair Removal", clinic_name: "Vedara Care", overdue_days: "7", booking_link: "https://zeva.care/book" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.POST_TREATMENT_MESSAGE,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Post Treatment Message",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Send aftercare instructions after treatment.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "after_event", offsetMinutes: 1440 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, we hope you are doing well after your {{treatment_name}} at {{clinic_name}}.\nAftercare: {{aftercare_instructions}}",
    sample: { patient_name: "Rahul", treatment_name: "Laser Hair Removal", clinic_name: "Vedara Care", aftercare_instructions: "Avoid sun exposure for 48 hours and apply soothing lotion." },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PREPARATION_REMINDER,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Preparation Reminder",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Pre-procedure prep instructions before appointment.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "before_event", offsetMinutes: -1440 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, reminder for your upcoming {{treatment_name}} on {{date}} at {{time}}.\nPrep instructions: {{preparation_instructions}}",
    sample: { patient_name: "Rahul", treatment_name: "Laser Hair Removal", date: "15 Aug 2026", time: "5:00 PM", preparation_instructions: "Shave treatment area 24 hours prior to session." },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REPORT_AVAILABLE,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Report Available",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Diagnostic or treatment report uploaded.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "after_event", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your {{report_name}} from {{clinic_name}} is now available. View report: {{report_link}}",
    sample: { patient_name: "Rahul", report_name: "Skin Analysis Report", clinic_name: "Vedara Care", report_link: "https://zeva.care/reports/r901" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.DOCUMENT_AVAILABLE,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Document Available",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "New medical document attached to record.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, a new document ({{document_name}}) has been shared by {{clinic_name}}. View document: {{document_link}}",
    sample: { patient_name: "Rahul", document_name: "Consent Form Copy", clinic_name: "Vedara Care", document_link: "https://zeva.care/docs/d102" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PRESCRIPTION_AVAILABLE,
    category: NOTIFICATION_CATEGORIES.FOLLOWUP,
    label: "Prescription Available",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Digital prescription issued by provider.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "after_event", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your prescription from {{clinic_name}} is ready. View prescription: {{prescription_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", prescription_link: "https://zeva.care/rx/p402" },
  },

  // ============================================================
  // 5. PATIENT ENGAGEMENT
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.BIRTHDAY_GREETING,
    category: NOTIFICATION_CATEGORIES.ENGAGEMENT,
    label: "Birthday Greeting",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient's birthday date.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "🎂 Happy Birthday {{patient_name}}! Everyone at {{clinic_name}} wishes you a wonderful birthday.",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.BIRTHDAY_OFFER,
    category: NOTIFICATION_CATEGORIES.ENGAGEMENT,
    label: "Birthday Offer",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Birthday discount or special offer unlocked.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "🎉 Happy Birthday {{patient_name}}! Enjoy {{discount_percentage}} OFF selected services this month at {{clinic_name}}. Book Now: {{booking_link}}",
    sample: { patient_name: "Rahul", discount_percentage: "15%", clinic_name: "Vedara Care", booking_link: "https://zeva.care/bday-offer" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PATIENT_INACTIVE,
    category: NOTIFICATION_CATEGORIES.ENGAGEMENT,
    label: "Patient Inactive",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "No clinic visits for configured duration (e.g. 90 days).", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, we haven't seen you at {{clinic_name}} in a while! Reconnect with us: {{reengagement_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", reengagement_link: "https://zeva.care/welcome-back" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.PATIENT_REACTIVATION,
    category: NOTIFICATION_CATEGORIES.ENGAGEMENT,
    label: "Patient Reactivation",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Re-engagement campaign sent to lapsed patients.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, we miss you at {{clinic_name}}! Here is a special offer: {{offer_name}}. Book your session today: {{booking_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", offer_name: "20% OFF Next Treatment", booking_link: "https://zeva.care/reactivate" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.ANNIVERSARY,
    category: NOTIFICATION_CATEGORIES.ENGAGEMENT,
    label: "Anniversary",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Anniversary of patient's first clinic visit.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "🌟 Happy {{anniversary_years}}-Year Anniversary {{patient_name}}! Thank you for being a valued patient at {{clinic_name}}.",
    sample: { patient_name: "Rahul", anniversary_years: "1", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.LOYALTY_REWARD,
    category: NOTIFICATION_CATEGORIES.ENGAGEMENT,
    label: "Loyalty Reward",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Loyalty points or reward tier unlocked.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, you earned {{reward_points}} reward points at {{clinic_name}}! Reward: {{reward_name}}. Redeem points: {{redeem_link}}",
    sample: { patient_name: "Rahul", reward_points: "250", reward_name: "Free Consultation Voucher", clinic_name: "Vedara Care", redeem_link: "https://zeva.care/rewards" },
  },

  // ============================================================
  // 6. OFFERS & REFERRALS
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.NEW_OFFER,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "New Offer",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "New promotional offer launched by clinic.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "🎁 Special Offer at {{clinic_name}}: {{offer_name}}! {{offer_description}}. Valid until {{expiry_date}}. Book now: {{booking_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", offer_name: "Summer Glow Package", offer_description: "3 Sessions for AED 999", expiry_date: "31 Aug 2026", booking_link: "https://zeva.care/offers/glow" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.OFFER_EXPIRING,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "Offer Expiring",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Promotional offer expires soon.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "before_event", offsetMinutes: -2880 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your offer {{offer_name}} at {{clinic_name}} expires on {{expiry_date}}. Don't miss out: {{booking_link}}",
    sample: { patient_name: "Rahul", offer_name: "Summer Glow Package", clinic_name: "Vedara Care", expiry_date: "31 Aug 2026", booking_link: "https://zeva.care/offers/glow" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.OFFER_REDEEMED,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "Offer Redeemed",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient redeems promotional offer.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your offer {{offer_name}} was successfully redeemed at {{clinic_name}} on {{redeem_date}}.",
    sample: { patient_name: "Rahul", offer_name: "Summer Glow Package", clinic_name: "Vedara Care", redeem_date: "12 Aug 2026" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REFERRAL_CREATED,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "Referral Created",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient generates a referral link.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, share {{clinic_name}} with your friends! Send them your referral link: {{referral_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", referral_link: "https://zeva.care/ref/rahul10" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REFERRAL_COMPLETED,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "Referral Completed",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Referred friend completes first visit.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Great news {{patient_name}}! Your friend {{referral_name}} visited {{clinic_name}}. You earned {{reward_points}} reward points!",
    sample: { patient_name: "Rahul", referral_name: "Priya", clinic_name: "Vedara Care", reward_points: "100" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REFERRAL_REWARD_EARNED,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "Referral Reward Earned",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Referral reward points added to account.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, you have earned a referral reward: {{reward_description}}! Redeem now: {{redeem_link}}",
    sample: { patient_name: "Rahul", reward_description: "AED 100 Clinic Credit", redeem_link: "https://zeva.care/rewards/claim" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REFERRAL_REWARD_USED,
    category: NOTIFICATION_CATEGORIES.OFFER,
    label: "Referral Reward Used",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Referral credit applied to invoice.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: true,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, your referral reward {{reward_name}} was successfully applied to your invoice at {{clinic_name}}.",
    sample: { patient_name: "Rahul", reward_name: "AED 100 Clinic Credit", clinic_name: "Vedara Care" },
  },

  // ============================================================
  // 7. FEEDBACK
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.FEEDBACK_REQUEST,
    category: NOTIFICATION_CATEGORIES.FEEDBACK,
    label: "Feedback Request",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Post-appointment feedback survey.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 1440 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, how was your experience at {{clinic_name}} today? Share your quick feedback: {{feedback_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", feedback_link: "https://zeva.care/feedback/f102" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.REVIEW_REQUEST,
    category: NOTIFICATION_CATEGORIES.FEEDBACK,
    label: "Review Request",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Google / public review invitation.", conditions: {} },
    channels: [
      { channel: "whatsapp", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "email", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "after_event", offsetMinutes: 2880 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Hi {{patient_name}}, if you enjoyed your visit to {{clinic_name}}, please leave us a 5-star Google review: {{review_link}}",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", review_link: "https://g.page/r/vedara-care/review" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.NEGATIVE_FEEDBACK_ALERT,
    category: NOTIFICATION_CATEGORIES.FEEDBACK,
    label: "Negative Feedback Alert",
    isEnabled: true,
    isProtected: false,
    trigger: { event: "Patient submits rating below clinic threshold (e.g. <3 stars).", conditions: {} },
    channels: [
      { channel: "email", recipient: "staff", isEnabled: true, priority: 1 },
      { channel: "app_push", recipient: "staff", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: false,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "⚠️ Negative Feedback Alert: Patient {{patient_name}} left a rating for {{clinic_name}}.\nComment: \"{{feedback_text}}\"",
    sample: { patient_name: "Rahul", clinic_name: "Vedara Care", feedback_text: "Wait time was too long at reception." },
  },

  // ============================================================
  // 8. SECURITY
  // ============================================================
  {
    notificationTypeKey: NOTIFICATION_TYPES.NEW_LOGIN,
    category: NOTIFICATION_CATEGORIES.SECURITY,
    label: "New Login",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Account accessed from a new device or IP.", conditions: {} },
    channels: [
      { channel: "email", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "app_push", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Security Alert: New login detected for {{patient_name}} at {{login_time}} from {{ip_address}} (Device: {{device_info}}). If this wasn't you, please secure your account immediately.",
    sample: { patient_name: "Rahul", login_time: "5:12 PM", ip_address: "192.168.1.1", device_info: "iPhone 15 Pro" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.ACCOUNT_CHANGED,
    category: NOTIFICATION_CATEGORIES.SECURITY,
    label: "Account Changed",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Password, phone, or email updated.", conditions: {} },
    channels: [
      { channel: "email", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "app_push", recipient: "patient", isEnabled: true, priority: 2 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Security Notice: Your ZEVA account {{change_type}} was updated on {{change_date}}. Contact {{clinic_name}} if you did not initiate this change.",
    sample: { patient_name: "Rahul", change_type: "phone number", change_date: "12 Aug 2026", clinic_name: "Vedara Care" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.CONSENT_CHANGED,
    category: NOTIFICATION_CATEGORIES.SECURITY,
    label: "Consent Changed",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Medical or data consent updated.", conditions: {} },
    channels: [
      { channel: "email", recipient: "patient", isEnabled: true, priority: 1 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "Consent Update: {{patient_name}}, your {{consent_type}} consent status at {{clinic_name}} was updated to {{consent_status}}.",
    sample: { patient_name: "Rahul", consent_type: "Medical Procedure Consent", clinic_name: "Vedara Care", consent_status: "Approved" },
  },
  {
    notificationTypeKey: NOTIFICATION_TYPES.IMPORTANT_SECURITY_EVENT,
    category: NOTIFICATION_CATEGORIES.SECURITY,
    label: "Important Security Event",
    isEnabled: true,
    isProtected: true,
    trigger: { event: "Critical security alert (MFA reset, suspicious activity).", conditions: {} },
    channels: [
      { channel: "email", recipient: "patient", isEnabled: true, priority: 1 },
      { channel: "app_push", recipient: "patient", isEnabled: true, priority: 2 },
      { channel: "sms", recipient: "patient", isEnabled: true, priority: 3 },
    ],
    timing: { mode: "immediate", offsetMinutes: 0 },
    bypassQuietHours: true,
    respectMarketingPreference: false,
    preventDuplicateForSameEvent: true,
    template: "⚠️ Critical Security Event: {{event_type}} occurred for your account on {{event_date}}. Please verify your security settings.",
    sample: { patient_name: "Rahul", event_type: "Password Reset Request", event_date: "12 Aug 2026" },
  },
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================

export const getAllNotificationTypes = () => Object.values(NOTIFICATION_TYPES);

export const getAllCategories = () => Object.values(NOTIFICATION_CATEGORIES);

export const isProtectedNotification = (typeKey) =>
  PROTECTED_NOTIFICATION_TYPES.includes(typeKey);

export const isMarketingNotification = (typeKey) =>
  MARKETING_NOTIFICATION_TYPES.includes(typeKey);

export const isStaffAlertNotification = (typeKey) =>
  STAFF_ALERT_NOTIFICATION_TYPES.includes(typeKey);

export const getNotificationSettingSeed = (typeKey) =>
  notificationData.find((item) => item.notificationTypeKey === typeKey) || null;

export const getCategoryLabel = (category) => {
  const labels = {
    [NOTIFICATION_CATEGORIES.PAYMENT]: "Payment & Billing",
    [NOTIFICATION_CATEGORIES.APPOINTMENT]: "Appointments",
    [NOTIFICATION_CATEGORIES.PACKAGE]: "Packages & Memberships",
    [NOTIFICATION_CATEGORIES.FOLLOWUP]: "Follow-up & Treatment",
    [NOTIFICATION_CATEGORIES.ENGAGEMENT]: "Patient Engagement",
    [NOTIFICATION_CATEGORIES.OFFER]: "Offers & Referrals",
    [NOTIFICATION_CATEGORIES.FEEDBACK]: "Feedback",
    [NOTIFICATION_CATEGORIES.SECURITY]: "Security",
  };
  return labels[category] || category;
};

export const getCategoryIcon = (category) => {
  const icons = {
    [NOTIFICATION_CATEGORIES.PAYMENT]: "💰",
    [NOTIFICATION_CATEGORIES.APPOINTMENT]: "📅",
    [NOTIFICATION_CATEGORIES.PACKAGE]: "📦",
    [NOTIFICATION_CATEGORIES.FOLLOWUP]: "🏥",
    [NOTIFICATION_CATEGORIES.ENGAGEMENT]: "🎯",
    [NOTIFICATION_CATEGORIES.OFFER]: "🎁",
    [NOTIFICATION_CATEGORIES.FEEDBACK]: "⭐",
    [NOTIFICATION_CATEGORIES.SECURITY]: "🔒",
  };
  return icons[category] || "📧";
};

export const getNotificationsGroupedByCategory = () => {
  const grouped = {};
  for (const category of Object.values(NOTIFICATION_CATEGORIES)) {
    grouped[category] = [];
  }
  for (const item of notificationData) {
    if (grouped[item.category]) {
      grouped[item.category].push(item);
    }
  }
  return grouped;
};
